# ---- Flask Backend ----
FROM python:3.12-slim

# set working directory
WORKDIR /app

# copy backend files
COPY backend/ /app/

# install dependencies
RUN pip install --no-cache-dir flask flask-bcrypt flask-cors pymongo

# expose Flask port
EXPOSE 5000

# set env (optional: use .env file for secrets)
ENV FLASK_ENV=production

CMD ["python", "app.py"]

